services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fast-spreadsheets
    ports:
      - "5001:5001"
    networks:
      - app_network
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: src:create_app()
networks:
  app_network:
    driver: bridge